### PR TITLE
Don't include build user, date and host in binaries.

### PR DESCRIPTION
**Pull request by jelmer**
This makes the build unreproducible.

### CODE REVIEW

**Comment by nicowilliams** [comment]
There's also `include/NTMakefile`.

The user/date/host info might be useful in some cases.  Maybe we should have a configuration option for it.

**Comment by quanah** [comment]
It's fairly traditional for lots of software to include that information, and it can be extremely useful information to have.

**Comment by nicowilliams** [comment]
@quanah Absolutely, however, for non-release builds it does make the build non-repeatable.  That's a problem.  We should want a `--release` or some such option to `./configure`, or perhaps a make variable.

**Comment by nicowilliams** [comment]
I'll try and add a `--release` or `--enable-release` option to `./configure` before 7.1.

**Pull request closed without merging**
