### PR TITLE
Follow-up PAC related tests

### PR DESCRIPTION
**Pull request by iboukris**
CC @lhoward

### CODE REVIEW

**Comment by lhoward** [comment]
Principal inside the PAC, do you mean inside the ticket? Or does this comment refer to the recent commit where we verify ticket cname matches logon info?

**Comment by iboukris** [comment]
> Principal inside the PAC, do you mean inside the ticket? Or does this comment refer to the recent commit where we verify ticket cname matches logon info?

The latter, if you revert that commit the test will fail.

**Comment by iboukris** [comment]
Recall that test_ap_req now verifies the PAC by default.

**Comment by lhoward** [comment]
Ah, excellent. Merging!

**Pull request merged**
