### PR TITLE
WinCNG reusable hash support

### PR DESCRIPTION
**Pull request by lhoward**
Untested

### CODE REVIEW

**Comment by lhoward** [comment]
Actually the latter statement isn't quite true – `wincng_md_hash_cleanup()` does need to be called from `EVP_DigestInit_ex()` too, in the case where the underlying digest changes. It turns out we don't need to change the provider interface at all, we just need to avoid calling `BCryptCreateHash()` if the hash object already exists.

(Of course, I realized this after cleaning up the provider interface... oh well. I'll omit those changes for now.)

**Comment by lhoward** [comment]
Question: given the version information is retrieved directly from the PEB, is it pointless caching the result of `IsWindows8OrGreater()`?

**Comment by nicowilliams** [comment]
What is PEB?

Anyways, patch LGTM.  Jeff might want to review.

**Comment by jaltman** [comment]
@nicowilliams  PEB is the Windows Process Environment Block 
https://docs.microsoft.com/en-us/windows/win32/api/winternl/ns-winternl-peb

**Comment by lhoward** [comment]
I’ll see if I can conduct some performance tests today.

**Comment by jaltman** [comment]
Given the number of statements that must be executed during the IsWindows8OrGreater() implementation I believe the caching is worthwhile.   Perhaps the caching should be within each of the IsWindowsXXX() functions so it benefits all callers.

**Comment by jaltman** [comment]
I've successfully tested this change on  Windows 10 [Version 10.0.19033.1].   
I still need to test on  Windows 7 [Version 6.1.7601].

**Comment by jaltman** [comment]
This change has been successfully tested on Windows 7 [Version 6.1.7601].

**Pull request merged**
