### PR TITLE
RFC4757/padding fixes

### PR DESCRIPTION
**Pull request by lhoward**
Fixes for #739

* gss_unwrap_iov() with rc4-hmac (RFC4757) encryption types would fail unless GSS_C_DCE_STYLE was specified, as an incorrect length was passed to _gssapi_verify_mech_header(). (The correct length is the header length for GSS_C_DCE_STYLE, and the wrap token length otherwise.)

* RFC 4121/4757 don't require padding as they operate as stream ciphers. Make the PADDING buffer optional when using these encryption types with gss_wrap_iov() and gss_unwrap_iov().

### CODE REVIEW

**Comment by jborean93** [comment]
See https://github.com/heimdal/heimdal/issues/739#issuecomment-657048663, when testing in my environment this not only fixes the issue where a PADDING buffer was required by Heimdal but shouldn't have been, it also fixes the RC4 decryption for the peculiar case that WinRM uses.

**Comment by abartlet** [comment]
Testing in Samba I had to revert 4b543b727a3a692e5b1d52620ba740944d565046 otherwise Heimdal/Heimdal with RC4 crypto failed connecting a Samba client to a Samba AD DC over DCE/RPC (so the DCE_STYLE case).

**Comment by lhoward** [comment]
Where is it failing?

**Comment by abartlet** [comment]
"make test TESTS=vampire_2000_dc" in Samba:
    
    gss_unwrap_iov failed:  A token was invalid: unknown mech-code 0 for mech 1 2 840 113554 1 2 2
    gssapi_unseal_packet(hdr_signing=1,sig_size=45,data=128,pdu=160) failed: NT_STATUS_ACCESS_DENIED

**Comment by lhoward** [comment]
Is `_gssapi_verify_mech_header()` failing? What are the input IOV lengths?

**Comment by abartlet** [comment]
Yes, it seems _gssapi_verify_mech_header() returns -1.

```
(gdb) p iov
$1 = {{type = 2, buffer = {length = 45, value = 0x564dfde07860}}, {type = 11, buffer = {length = 24, value = 0x564dfe1dbca0}}, {type = 1, buffer = {length = 128, value = 0x564dfe1dbcb8}}, {type = 11, buffer = {length = 8, value = 0x564dfe1dbd38}}}
```

```
Breakpoint 3, _gssapi_verify_mech_header (str=str@entry=0x7ffe0b9d6960, total_len=173, mech=0x7f3363a9a240 <__gss_krb5_mechanism_oid_desc>) at ../../source4/heimdal/lib/gssapi/krb5/decapsulate.c:73
73      {
(gdb) n
77          mech_len = _gsskrb5_get_mech (*str, total_len, &p);
(gdb) n
78          if (mech_len < 0)
(gdb) p mech_len
$2 = -1
(gdb) n
_gssapi_unwrap_iov_arcfour (minor_status=minor_status@entry=0x7ffe0b9d6b64, ctx=ctx@entry=0x564dfe2f0170, context=0x564dfdcaf5c0, pconf_state=pconf_state@entry=0x7ffe0b9d6b6c, pqop_state=pqop_state@entry=0x7ffe0b9d6b68, iov=iov@entry=0x7ffe0b9d6b70, iov_count=4, key=0x564dfe3b1de0)
    at ../../source4/heimdal/lib/gssapi/krb5/arcfour.c:1218
1218        if (ret) {
(gdb) 
_gk_unwrap_iov (minor_status=0x7ffe0b9d6b64, context_handle=0x564dfe2f0170, conf_state=0x7ffe0b9d6b6c, qop_state=0x7ffe0b9d6b68, iov=0x7ffe0b9d6b70, iov_count=4) at ../../source4/heimdal/lib/gssapi/krb5/aeap.c:121
121             break;
(gdb) 
128         krb5_free_keyblock(context, key);
(gdb) 
129         return ret;
(gdb) 
gssapi_unseal_packet (gssapi_context=<optimized out>, mech=0x7f3363a9a240 <__gss_krb5_mechanism_oid_desc>, hdr_signing=hdr_signing@entry=true, 
    data=data@entry=0x564dfe219998 "\375DW@\235$%\360.\313{h\226oЖ\f($C\225\265\260\322\356\030%\241`\331@\340\004a\006\245\345ra\330X*\315rg\207\363r\322\322\367\250(PG]I\377\316f0F\213J\223DK#", length=length@entry=128, whole_pdu=whole_pdu@entry=0x564dfe219980 "\005", pdu_length=160, 
    sig=0x7ffe0b9d6ca0) at ../../auth/kerberos/gssapi_helper.c:289
289             if (GSS_ERROR(maj_stat)) {
(gdb) p iov
$3 = {{type = 2, buffer = {length = 45, value = 0x564dfe3d43a0}}, {type = 11, buffer = {length = 24, value = 0x564dfe219980}}, {type = 1, buffer = {length = 128, value = 0x564dfe219998}}, {type = 11, buffer = {length = 8, value = 0x564dfe219a18}}}
```

**Comment by lhoward** [comment]
Hmm, I wonder how `verify_len` (the second argument to `_gssapi_verify_mech_header()`) is 173, when it should just be `header->buffer.length` when `GSS_C_DCE_STYLE` is set.

```c
    verify_len = header->buffer.length;

    if (!IS_DCE_STYLE(context)) {
        for (i = 0; i < iov_count; i++) {
            /* length in header also includes data and padding */
            if (GSS_IOV_BUFFER_TYPE(iov[i].type) == GSS_IOV_BUFFER_TYPE_DATA)
                verify_len += iov[i].buffer.length;
        }

        if (padding)
            verify_len += padding->buffer.length;
    }

    _p = header->buffer.value;

    ret = _gssapi_verify_mech_header(&_p,
                                     verify_len,
                                     GSS_KRB5_MECHANISM);
```

**Comment by lhoward** [comment]
Ah, I think I've found the bug. Hang 5.

**Comment by lhoward** [comment]
Please try 0dd19003082f50b729328a4161b4462d6e06ed05

**Comment by abartlet** [comment]
Thanks, that works for me.

**Pull request merged**
