### PR TITLE
gssapi: SPNEGO does not reset NTLM RC4 state (#509)

### PR DESCRIPTION
**Pull request by lhoward**
Untested

### CODE REVIEW

**Comment by lhoward** [comment]
cc @simo5

**Comment by lhoward** [comment]
Really we need to import Apple's NTLM implementation (or maybe Samba has one?)

**Comment by nicowilliams** [comment]
@lhoward do we also need to restore sequence numbers?

**Comment by lhoward** [comment]
@nicowilliams that is done by `_gss_ntlm_set_key()`

**Comment by nicowilliams** [comment]
Ah, I'd missed that.

**Comment by simo5** [comment]
@lhoward I think you should just support/use https://github.com/simo5/gss-ntlmssp

**Comment by nicowilliams** [comment]
Could this have been implemented by having SPNEGO export the NTLM sec context prior to making the MIC, then re-import it at the end?

**Comment by simo5** [comment]
> Could this have been implemented by having SPNEGO export the NTLM sec
context prior to making the MIC, then re-import it at the end?

I do not recall all details, but I remember considering that option
when I implemented gss-ntlmssp and the required fixes to MIT SPNEGO
implementation, and didn't go that way. So there may well be some
detail that won't work with a full export/import.

**Comment by nicowilliams** [comment]
@simo5 that sounds familiar.  ISTR talking about this before.  I also don't recall the details, so I'm going to assume that this is the right fix.

**Comment by lhoward** [comment]
I think in terms of coding style and licensing, ingesting the Apple changes is probably the best way forward.

**Comment by simo5** [comment]
I was more concerned about correctness.
I have basically only one isue left with gss-ntlmssp, but I corrected ton of stuff that is broken in many implementations, including Heimdal one.
But up to you anyway

**Pull request merged**
