### PR TITLE
kdc: validate sname in TGS-REQ

### PR DESCRIPTION
**Pull request by quanah**
For #849 
In tgs_build_reply(), validate the server name in the TGS-REQ is present before
dereferencing.

### CODE REVIEW

**Comment by lhoward** [comment]
First commit was buggy

**Comment by quanah** [comment]
> 
> 
> First commit was buggy

Thanks, updated PR.

**Comment by lhoward** [comment]
Pretty sure this was fixed by 0417114794, so closing.

**Comment by abartlet** [comment]
Isn't that only in master and not 7.1?

**Comment by lhoward** [comment]
Ah, whoops, my bad. Reopening.

**Comment by jaltman** [comment]
278d9738c is the cherry-pick to 7-1-branch

**Pull request closed without merging**
