### PR TITLE
Introduce HDB_F_FOR_S4U2SELF

### PR DESCRIPTION
**Pull request by metze-samba**
The will be used to allow the addition of special SIDS into the
    PAC:
    
    - SID_AUTHENTICATION_AUTHORITY_ASSERTED_IDENTITY (S-1-18-1):
    
      This is added during the AS-REQ/AS-REP exchange after
      pre-authentication was successful.
    
    - SID_SERVICE_ASSERTED_IDENTITY (S-1-18-2):
      This is added during S4U2Self PAC creation.
      It won't replace a possible
      SID_AUTHENTICATION_AUTHORITY_ASSERTED_IDENTITY
      during S4U2Proxy.

### CODE REVIEW

**Comment by lhoward** [comment]
Not opposed, but can it be determined by the plug-in interrogating the request for S4U2Self PA data?

**Comment by lhoward** [comment]
Also I’d remove `FOR` from the macro name.

**Comment by lhoward** [comment]
I think it should be fine to call `kdc_request_get_req()` and then `krb5_find_padata(KRB5_PADATA_FOR_USER)` as there are no successful paths where `KRB5_PADATA_FOR_USER` is present and S4U2Self is not performed. Closing for now, please reopen if you disagree.

**Comment by metze-samba** [comment]
> I think it should be fine to call `kdc_request_get_req()` and then `krb5_find_padata(KRB5_PADATA_FOR_USER)` as there are no successful paths where `KRB5_PADATA_FOR_USER` is present and S4U2Self is not performed. Closing for now, please reopen if you disagree.

Yes, that's fine for now, when we add support for the new style PA-S4U-X509-USER S4U2Self version,
but I guess then we could have a 'bool kdc_request_get_s4u2self_used()' for easy access.

**Pull request closed without merging**
