### PR TITLE
Avoid make dist fail when doxyout/ does not exist

### PR DESCRIPTION
**Pull request by vdukhovni**

### CODE REVIEW

**Comment by vdukhovni** [comment]
I have doxygen installed, and yet that directory does not exist initially when I run "make dist".

**Comment by vdukhovni** [comment]
Is there something doxygen-related I am neglecting to do after:
```
./autogen.sh
./configure ...
```
and before
```
make dist
```

**Comment by nicowilliams** [comment]
Oh, maybe the sequence is:

```
./autogen.sh
./configure ...
make doc
make dist
```

**Comment by vdukhovni** [comment]
Nope, "make doc" is a NOP (doc already exists).

**Comment by vdukhovni** [comment]
Also ``cd doc; make`` does not create any "doxyout" directories.

**Comment by nicowilliams** [comment]
Huh.  Looking...

**Comment by nicowilliams** [comment]
You have to `(cd $objdir/doc && make doxyout)`.

**Comment by nicowilliams** [comment]
If the `doxyout` directory doesn't exist `make doxyout` will whine but build it anyways, and the initial absence of `doxyout` will not affect the results.

**Comment by vdukhovni** [comment]
On FreeBSD, make runs the shell command with ``set -e`` by default.

**Comment by vdukhovni** [comment]
The patch avoids having the ``find ...`` blow up in ``make doxyout``

**Comment by nicowilliams** [comment]
```
find: ‘/home/nico/ws/heimdal/doc/doxyout’: No such file or directory
base
hdb
hx509
gssapi
/home/nico/ws/heimdal/lib/gssapi/mech/doxygen.c:129: warning: Found unknown command `\FIXME'
krb5
ntlm
wind
hcrypto
/home/nico/ws/heimdal/lib/hcrypto/evp-openssl.c:509: warning: parameters of member OSSL_CIPHER_ALGORITHM are not (all) documented
/home/nico/ws/heimdal/lib/hcrypto/evp-openssl.c:530: warning: parameters of member OSSL_CIPHER_ALGORITHM are not (all) documented
/home/nico/ws/heimdal/lib/hcrypto/evp-wincng.c:459: warning: parameters of member WINCNG_CIPHER_ALGORITHM are not (all) documented
/home/nico/ws/heimdal/lib/hcrypto/evp-wincng.c:474: warning: parameters of member WINCNG_CIPHER_ALGORITHM are not (all) documented
/home/nico/ws/heimdal/lib/hcrypto/des.c:764: warning: return type of member DES_cbc_cksum is not documented
```

The only differences to a previously-existing `doxyout` directory I had lying around were datetimes and Heimdal version numbers.

**Comment by nicowilliams** [comment]
Why don't we just add a `mkdir -p @(srcdir)/doxyout`?

**Pull request merged**
