### PR TITLE
Update bits.c to fix memory leak

### PR DESCRIPTION
**Pull request by Hyxl1017**
p will not longer be use add after line 140,so add "free(q);" at line 140 to fix memory leak.

### CODE REVIEW

**Comment by lhoward** [comment]
Did you check this actually compiles? `q` is not defined anywhere.

**Comment by lhoward** [comment]
To fix this properly, you're going to need a non-const alias of the `p` base pointer that can be freed at the *end* of the program, as `hb` is used throughout. Please resubmit.

**Comment by lhoward** [comment]
Or you could just make `hb` non-const, and check `argc >= 2` at the end of the program before calling `free(hb)`.

**Comment by lhoward** [comment]
Closing, awaiting resubmission.

**Comment by Hyxl1017** [comment]
thanks for advice.

**Pull request closed without merging**
