### PR TITLE
Skip mdb_stat test when the command is not available

### LINKED ISSUE #251: If mdb_stat is not present, one test fails
checking that principals in DB == entries in LMDB
./check-iprop: line 388: mdb_stat: command not found
./check-iprop: line 389: [: : integer expression expected
FAIL: check-iprop

### PR DESCRIPTION
**Pull request by vdukhovni**
This should resolve #251

### CODE REVIEW

**Comment by nicowilliams** [comment]
LGTM.

**Comment by nicowilliams** [comment]
The commit message should say "fix @251" so that when you push this then #251 gets closed.

**Comment by quanah** [comment]
I am testing locally and will update once that's complete.

**Comment by quanah** [comment]
While "resolves" is not a valid keyword, there are several words one can use:

By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into master, it will also automatically close the issue.

**Comment by quanah** [comment]
Looks good.

Before:
```
make  check-authz check-canon check-cc check-delegation check-des check-digest check-fast check-kadmin check-hdb-mitdb check-kdc check-kdc-weak check-keys check-kpasswdd check-pkinit check-iprop check-referral check-tester check-uu
  GEN    check-iprop
./check-iprop: line 388: mdb_stat: command not found
./check-iprop: line 389: [: : integer expression expected
FAIL: check-iprop
```
With this fix:

```
make  check-authz check-canon check-cc check-delegation check-des check-digest check-fast check-kadmin check-hdb-mitdb check-kdc check-kdc-weak check-keys check-kpasswdd check-pkinit check-iprop check-referral check-tester check-uu
  GEN    check-iprop
PASS: check-iprop
```

**Pull request merged**
