### PR TITLE
Fix a memory leak in spnego acceptor_start().

### PR DESCRIPTION
**Pull request by yasuoka**

### CODE REVIEW

**Comment by yasuoka** [comment]
Previous commit had not fixed the problem.  I pushed updated commit.

**Comment by nicowilliams** [comment]
Did you actually observe a leak?

**Comment by nicowilliams** [comment]
We should make `gss_release_oid()` do nothing -- it should never have existed.  `gss_str_to_oid()` should intern and its outputs never freed (except at library unload time, and arguably we should not support library unload).

**Comment by nicowilliams** [comment]
We're going to close this and instead make sure that `gss_release_oid()` does nothing.  Heimdal doesn't offer `gss_str_to_oid()`, so that's good.

**Comment by yasuoka** [comment]
> Did you actually observe a leak?
Yes, a leak actually happened.

Fixing the problem by #447 will make sense.  Thank for fixing the issue.

**Pull request closed without merging**
